insert into public.agent_categories (
  slug,
  name_en,
  name_zh,
  description_en,
  description_zh,
  icon,
  sort_order
)
values
  ('customer-support', 'Customer Support', '客服', 'Agents for customer service and support workflows.', '用于客户服务和支持流程的 Agent。', 'headphones', 10),
  ('sales-lead-generation', 'Sales & Lead Generation', '销售获客', 'Agents that qualify leads and support sales teams.', '用于线索筛选和销售支持的 Agent。', 'target', 20),
  ('ecommerce', 'E-commerce', '电商', 'Agents for online stores, orders, and product support.', '用于网店、订单和商品咨询的 Agent。', 'shopping-bag', 30),
  ('education', 'Education', '教育培训', 'Agents for schools, courses, and coaching services.', '用于学校、课程和培训服务的 Agent。', 'graduation-cap', 40),
  ('real-estate', 'Real Estate', '房地产', 'Agents for property inquiries and real estate lead capture.', '用于房产咨询和房地产获客的 Agent。', 'building', 50),
  ('legal', 'Legal', '法律咨询', 'Agents for legal intake and law firm operations.', '用于法律初筛和律所运营的 Agent。', 'scale', 60),
  ('healthcare-medical-beauty', 'Healthcare & Medical Beauty', '医疗医美', 'Agents for clinic, wellness, and medical beauty intake.', '用于诊所、健康服务和医美咨询的 Agent。', 'stethoscope', 70),
  ('restaurant-local-business', 'Restaurant & Local Business', '餐饮本地商家', 'Agents for restaurants and local service businesses.', '用于餐厅和本地服务商家的 Agent。', 'store', 80),
  ('content-creation', 'Content Creation', '内容创作', 'Agents for writing, summarization, and media workflows.', '用于写作、总结和媒体工作流的 Agent。', 'pen-tool', 90),
  ('research-analysis', 'Research & Analysis', '研究分析', 'Agents for research, monitoring, and business analysis.', '用于研究、监控和商业分析的 Agent。', 'chart-line', 100),
  ('internal-knowledge-base', 'Internal Knowledge Base', '企业知识库', 'Agents that answer from approved internal company knowledge.', '基于企业内部知识回答问题的 Agent。', 'book-open', 110),
  ('developer-tools', 'Developer Tools', '开发工具', 'Agents and workflows for software teams.', '面向软件团队的 Agent 和工作流。', 'code', 120),
  ('ai-news-monitoring', 'AI News Monitoring', 'AI 资讯监控', 'Agents that track AI news and produce briefings.', '用于 AI 资讯监控和简报生成的 Agent。', 'newspaper', 130),
  ('automation-workflows', 'Automation Workflows', '自动化工作流', 'Agents that automate recurring business workflows.', '用于自动化业务流程的 Agent。', 'workflow', 140)
on conflict (slug) do update set
  name_en = excluded.name_en,
  name_zh = excluded.name_zh,
  description_en = excluded.description_en,
  description_zh = excluded.description_zh,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.marketplace_agents (
  slug,
  owner_type,
  status,
  is_featured,
  is_verified,
  category_id,
  tags,
  pricing_type,
  price_usd,
  price_cny,
  delivery_type,
  supported_languages,
  demo_url,
  demo_enabled,
  rating,
  review_count,
  purchase_count,
  install_count,
  title_en,
  title_zh,
  short_description_en,
  short_description_zh,
  description_en,
  description_zh,
  features_en,
  features_zh,
  faq_en,
  faq_zh,
  setup_instructions_en,
  setup_instructions_zh,
  data_permissions_en,
  data_permissions_zh,
  version,
  changelog_en,
  changelog_zh,
  screenshots,
  video_url
)
values
  (
    'website-customer-support-agent',
    'platform',
    'approved',
    true,
    true,
    (select id from public.agent_categories where slug = 'customer-support'),
    array['customer-support', 'website-chatbot', 'lead-capture'],
    'one_time',
    499,
    3599,
    'website_chatbot',
    array['en', 'zh'],
    'https://demo.example.com/agents/website-customer-support',
    true,
    4.80,
    18,
    42,
    120,
    $$Website Customer Support Agent$$,
    $$网站客服 Agent$$,
    $$Answers common website questions and captures qualified leads.$$,
    $$回答网站常见问题并收集合格线索。$$,
    $$A ready-made website chatbot for businesses that need fast customer support coverage without hiring a larger support team.$$,
    $$适合企业网站的智能客服，可快速覆盖常见咨询并减少人工客服压力。$$,
    $$["Answer common website questions","Collect name, email, company, and intent","Escalate complex requests to the team"]$$::jsonb,
    $$["回答网站常见问题","收集姓名、邮箱、公司和需求意向","将复杂咨询转交给团队"]$$::jsonb,
    $$[{"question":"Can it use our website content?","answer":"Yes. Setup starts from approved pages, FAQs, and policy documents."},{"question":"Does it replace human support?","answer":"No. It handles first-line questions and escalates complex cases."}]$$::jsonb,
    $$[{"question":"可以使用我们网站的内容吗？","answer":"可以。配置时会使用已确认的网站页面、FAQ 和政策文档。"},{"question":"它会完全替代人工客服吗？","answer":"不会。它负责一线常见问题，并将复杂情况转交人工。"}]$$::jsonb,
    $$Connect approved website pages, add FAQ documents, configure escalation rules, and embed the chat widget.$$,
    $$连接已审核的网站页面，添加 FAQ 文档，配置转人工规则，并嵌入聊天组件。$$,
    $$Uses approved website and FAQ content. Does not require payment data or private customer records.$$,
    $$使用已审核的网站和 FAQ 内容，不需要支付数据或客户隐私档案。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'ecommerce-product-support-agent',
    'platform',
    'approved',
    true,
    true,
    (select id from public.agent_categories where slug = 'ecommerce'),
    array['ecommerce', 'product-support', 'orders'],
    'monthly',
    199,
    1399,
    'hosted_agent',
    array['en', 'zh'],
    'https://demo.example.com/agents/ecommerce-product-support',
    true,
    4.70,
    15,
    36,
    88,
    $$E-commerce Product Support Agent$$,
    $$电商产品客服 Agent$$,
    $$Guides shoppers through product questions, returns, and order help.$$,
    $$帮助买家咨询商品、退换货和订单问题。$$,
    $$A commerce support agent for product catalogs, shipping questions, return policies, and conversion-focused recommendations.$$,
    $$面向电商商品目录、物流、退换货政策和转化推荐的客服 Agent。$$,
    $$["Answer product questions","Explain shipping and return policies","Recommend products from guided needs"]$$::jsonb,
    $$["回答商品问题","解释物流与退换货政策","根据需求推荐商品"]$$::jsonb,
    $$[{"question":"Can it connect to a product catalog?","answer":"Yes. Phase 1 stores the model fields; integrations come later."},{"question":"Can it handle returns?","answer":"It can explain policies and collect return details for staff follow-up."}]$$::jsonb,
    $$[{"question":"可以连接商品目录吗？","answer":"可以。第一阶段先准备数据模型，后续接入集成。"},{"question":"可以处理退货吗？","answer":"可以解释政策并收集退货信息，交给团队跟进。"}]$$::jsonb,
    $$Upload product FAQs, policies, and sample product data before publishing the hosted agent.$$,
    $$上传商品 FAQ、政策和示例商品数据后，再发布托管 Agent。$$,
    $$Uses product, order policy, and support FAQ data. Order system integration is optional in later phases.$$,
    $$使用商品、订单政策和客服 FAQ 数据。订单系统集成可在后续阶段添加。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'real-estate-lead-agent',
    'platform',
    'approved',
    true,
    true,
    (select id from public.agent_categories where slug = 'real-estate'),
    array['real-estate', 'lead-qualification', 'sales'],
    'one_time',
    799,
    5799,
    'website_chatbot',
    array['en', 'zh'],
    'https://demo.example.com/agents/real-estate-lead',
    true,
    4.90,
    21,
    31,
    64,
    $$Real Estate Lead Agent$$,
    $$房地产获客 Agent$$,
    $$Qualifies property buyers and routes serious leads to sales teams.$$,
    $$筛选购房客户并将高意向线索转给销售团队。$$,
    $$A lead capture assistant for real estate agencies that asks buyer intent, budget, location, and timeline questions.$$,
    $$帮助房地产机构收集购房意向、预算、区域和时间计划的获客助手。$$,
    $$["Qualify buyer intent","Collect budget and location preferences","Route high-intent leads"]$$::jsonb,
    $$["筛选购房意向","收集预算和区域偏好","转交高意向线索"]$$::jsonb,
    $$[{"question":"Can it book viewings?","answer":"It can collect viewing preferences and send them to the sales team."},{"question":"Can it support rental leads?","answer":"Yes. Questions can be adjusted for rental or purchase flows."}]$$::jsonb,
    $$[{"question":"可以预约看房吗？","answer":"可以收集看房偏好并发送给销售团队。"},{"question":"可以支持租赁线索吗？","answer":"可以。问题可以调整为租赁或购房流程。"}]$$::jsonb,
    $$Configure property types, service areas, budget bands, and team routing rules.$$,
    $$配置房产类型、服务区域、预算区间和团队分配规则。$$,
    $$Collects lead contact details and stated preferences. It should not request financial documents in demo mode.$$,
    $$收集线索联系方式和需求偏好。演示模式不应索取财务文件。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'restaurant-booking-agent',
    'platform',
    'approved',
    false,
    true,
    (select id from public.agent_categories where slug = 'restaurant-local-business'),
    array['restaurant', 'booking', 'local-business'],
    'monthly',
    99,
    699,
    'hosted_agent',
    array['en', 'zh'],
    'https://demo.example.com/agents/restaurant-booking',
    true,
    4.50,
    9,
    18,
    44,
    $$Restaurant Booking Agent$$,
    $$餐厅预约 Agent$$,
    $$Handles booking requests, FAQs, and private dining inquiries.$$,
    $$处理订位、常见问题和包间咨询。$$,
    $$A local restaurant agent for reservation intake, opening hours, menu questions, and event booking requests.$$,
    $$面向餐饮商家的预约、营业时间、菜单咨询和活动订位 Agent。$$,
    $$["Collect reservation requests","Answer hours and menu questions","Capture private dining inquiries"]$$::jsonb,
    $$["收集预约请求","回答营业时间和菜单问题","收集包间和活动咨询"]$$::jsonb,
    $$[{"question":"Does it confirm bookings automatically?","answer":"Phase 1 treats bookings as requests until calendar integration is added."},{"question":"Can it handle large parties?","answer":"Yes. It captures party size, time, and contact details."}]$$::jsonb,
    $$[{"question":"会自动确认预约吗？","answer":"第一阶段将预约作为请求处理，后续可接入日历。"},{"question":"可以处理多人聚餐吗？","answer":"可以收集人数、时间和联系方式。"}]$$::jsonb,
    $$Add opening hours, seating rules, menu links, and notification recipients.$$,
    $$添加营业时间、座位规则、菜单链接和通知接收人。$$,
    $$Collects booking contact information and party details. Payment details are not required.$$,
    $$收集预约联系方式和用餐信息，不需要支付信息。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'course-enrollment-agent',
    'platform',
    'approved',
    false,
    true,
    (select id from public.agent_categories where slug = 'education'),
    array['education', 'enrollment', 'training'],
    'one_time',
    599,
    4299,
    'website_chatbot',
    array['en', 'zh'],
    'https://demo.example.com/agents/course-enrollment',
    true,
    4.60,
    13,
    24,
    71,
    $$Course Enrollment Agent$$,
    $$课程招生 Agent$$,
    $$Explains courses, collects student goals, and books consultations.$$,
    $$介绍课程、收集学习目标并预约咨询。$$,
    $$An education enrollment agent for schools, bootcamps, and training companies that need better inquiry follow-up.$$,
    $$面向学校、训练营和培训机构的招生咨询 Agent，提升咨询转化效率。$$,
    $$["Explain course options","Collect learning goals","Prepare consultation handoff notes"]$$::jsonb,
    $$["介绍课程选择","收集学习目标","整理咨询交接信息"]$$::jsonb,
    $$[{"question":"Can it recommend courses?","answer":"Yes. It recommends based on stated goals and eligibility rules."},{"question":"Can counselors edit answers?","answer":"Yes. Content should be reviewed before publishing."}]$$::jsonb,
    $$[{"question":"可以推荐课程吗？","answer":"可以根据学习目标和报名条件推荐。"},{"question":"顾问可以修改回答吗？","answer":"可以。上线前应审核内容。"}]$$::jsonb,
    $$Add course catalog, eligibility rules, pricing notes, and counselor routing details.$$,
    $$添加课程目录、报名条件、价格说明和顾问分配信息。$$,
    $$Collects education goals and contact details. Sensitive student records are not required for the demo.$$,
    $$收集学习目标和联系方式，演示不需要敏感学生档案。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'medical-beauty-consultation-agent',
    'platform',
    'approved',
    false,
    true,
    (select id from public.agent_categories where slug = 'healthcare-medical-beauty'),
    array['medical-beauty', 'clinic', 'consultation'],
    'custom_quote',
    1200,
    8800,
    'custom_business_agent',
    array['en', 'zh'],
    'https://demo.example.com/agents/medical-beauty-consultation',
    true,
    4.70,
    11,
    12,
    29,
    $$Medical Beauty Consultation Agent$$,
    $$医美咨询 Agent$$,
    $$Pre-screens client needs and routes consultation requests.$$,
    $$初步了解客户需求并分配咨询请求。$$,
    $$A medical beauty consultation intake agent with clear disclaimers and appointment-oriented workflows.$$,
    $$用于医美咨询初筛、风险提示和预约流程的 Agent。$$,
    $$["Collect consultation goals","Explain non-diagnostic service information","Route requests to clinic staff"]$$::jsonb,
    $$["收集咨询目标","说明非诊断类服务信息","将请求转给机构人员"]$$::jsonb,
    $$[{"question":"Does it give medical advice?","answer":"No. It collects consultation context and directs users to qualified staff."},{"question":"Can it include disclaimers?","answer":"Yes. Safety and disclaimer content is part of setup."}]$$::jsonb,
    $$[{"question":"它会提供医疗建议吗？","answer":"不会。它收集咨询背景，并引导用户联系专业人员。"},{"question":"可以加入风险提示吗？","answer":"可以。安全说明和免责声明属于配置内容。"}]$$::jsonb,
    $$Add approved service descriptions, disclaimers, clinic routing, and appointment request rules.$$,
    $$添加已审核服务介绍、免责声明、机构分配和预约请求规则。$$,
    $$Collects consultation intent and contact details. Avoid entering medical records or diagnosis data in demo mode.$$,
    $$收集咨询意向和联系方式。演示模式避免输入病历或诊断数据。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'law-firm-intake-agent',
    'platform',
    'approved',
    false,
    true,
    (select id from public.agent_categories where slug = 'legal'),
    array['legal', 'intake', 'law-firm'],
    'monthly',
    299,
    2099,
    'hosted_agent',
    array['en', 'zh'],
    'https://demo.example.com/agents/law-firm-intake',
    true,
    4.60,
    8,
    16,
    33,
    $$Law Firm Intake Agent$$,
    $$律所客户初筛 Agent$$,
    $$Collects intake details and prepares cases for attorney review.$$,
    $$收集案件背景并整理给律师审核。$$,
    $$A law firm intake assistant for collecting structured case details while avoiding legal advice automation.$$,
    $$帮助律所结构化收集案情信息，同时避免自动化法律建议。$$,
    $$["Collect structured intake details","Classify matter type","Prepare attorney handoff summary"]$$::jsonb,
    $$["结构化收集案情","分类案件类型","生成律师交接摘要"]$$::jsonb,
    $$[{"question":"Does it provide legal advice?","answer":"No. It only collects information and routes it for attorney review."},{"question":"Can it screen conflict details?","answer":"It can collect basic conflict screening fields for staff review."}]$$::jsonb,
    $$[{"question":"它会提供法律建议吗？","answer":"不会。它只收集信息并交由律师审核。"},{"question":"可以收集利益冲突筛查信息吗？","answer":"可以收集基础筛查字段供团队审核。"}]$$::jsonb,
    $$Configure practice areas, disclaimers, intake fields, and routing rules.$$,
    $$配置业务领域、免责声明、初筛字段和分配规则。$$,
    $$Collects client-provided intake details. Confidentiality language should be reviewed by the firm.$$,
    $$收集客户主动提供的初筛信息。保密说明需由律所审核。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'internal-knowledge-base-agent',
    'platform',
    'approved',
    true,
    true,
    (select id from public.agent_categories where slug = 'internal-knowledge-base'),
    array['knowledge-base', 'internal-support', 'documents'],
    'custom_quote',
    1500,
    10800,
    'custom_business_agent',
    array['en', 'zh'],
    'https://demo.example.com/agents/internal-knowledge-base',
    true,
    4.90,
    27,
    19,
    58,
    $$Internal Knowledge Base Agent$$,
    $$企业知识库 Agent$$,
    $$Answers employee questions from approved internal documents.$$,
    $$基于企业内部资料回答员工问题。$$,
    $$A company knowledge assistant for SOPs, HR policies, onboarding documents, and internal support.$$,
    $$面向 SOP、人事制度、入职文档和内部支持的企业知识库助手。$$,
    $$["Answer from approved documents","Cite source document names","Escalate unanswered questions"]$$::jsonb,
    $$["基于已审核文档回答","引用来源文档名称","升级无法回答的问题"]$$::jsonb,
    $$[{"question":"Can it cite sources?","answer":"Yes. Source-aware answers are expected for internal knowledge use."},{"question":"Can access be restricted?","answer":"Yes. Role-based access should be added during auth and RLS phases."}]$$::jsonb,
    $$[{"question":"可以引用来源吗？","answer":"可以。企业知识库场景应支持来源提示。"},{"question":"可以限制访问权限吗？","answer":"可以。权限控制会在认证和 RLS 阶段加入。"}]$$::jsonb,
    $$Collect approved internal documents, define access rules, and configure unanswered-question routing.$$,
    $$收集已审核内部文档，定义访问规则，并配置无法回答问题的转交流程。$$,
    $$Uses company-provided documents. Sensitive documents should be permission-scoped before upload.$$,
    $$使用企业提供的文档。敏感文档上传前应先划分权限范围。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'ai-news-monitoring-agent',
    'platform',
    'approved',
    true,
    true,
    (select id from public.agent_categories where slug = 'ai-news-monitoring'),
    array['ai-news', 'monitoring', 'briefing'],
    'monthly',
    149,
    999,
    'workflow_template',
    array['en', 'zh'],
    'https://demo.example.com/agents/ai-news-monitoring',
    true,
    4.80,
    22,
    28,
    95,
    $$AI News Monitoring Agent$$,
    $$AI 资讯监控 Agent$$,
    $$Tracks AI news and sends concise business-ready summaries.$$,
    $$监控 AI 资讯并输出适合业务阅读的摘要。$$,
    $$A monitoring workflow for AI industry updates, competitor signals, and executive briefings.$$,
    $$用于 AI 行业动态、竞品信号和管理层简报的资讯监控工作流。$$,
    $$["Track selected AI topics","Summarize news for business readers","Prepare weekly briefing drafts"]$$::jsonb,
    $$["监控指定 AI 主题","为业务读者总结资讯","生成周报草稿"]$$::jsonb,
    $$[{"question":"Can sources be customized?","answer":"Yes. Sources and topic keywords can be configured."},{"question":"Does it publish automatically?","answer":"No. Briefings should be reviewed before sharing."}]$$::jsonb,
    $$[{"question":"可以自定义来源吗？","answer":"可以。来源和主题关键词都能配置。"},{"question":"会自动发布吗？","answer":"不会。简报建议审核后再分享。"}]$$::jsonb,
    $$Define topic keywords, sources, recipients, language, and briefing frequency.$$,
    $$定义主题关键词、来源、接收人、语言和简报频率。$$,
    $$Uses public news sources and configured keywords. Private competitive data is optional and should be reviewed.$$,
    $$使用公开资讯来源和配置关键词。私有竞品资料如需接入应先审核。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'youtube-video-summary-agent',
    'platform',
    'approved',
    false,
    true,
    (select id from public.agent_categories where slug = 'content-creation'),
    array['youtube', 'summary', 'content'],
    'one_time',
    79,
    499,
    'prompt_template',
    array['en', 'zh'],
    'https://demo.example.com/agents/youtube-video-summary',
    true,
    4.40,
    7,
    33,
    140,
    $$YouTube Video Summary Agent$$,
    $$YouTube 视频总结 Agent$$,
    $$Turns video links into summaries, highlights, and action items.$$,
    $$将视频链接转为摘要、重点和行动项。$$,
    $$A content productivity agent for summarizing videos, extracting key takeaways, and preparing notes.$$,
    $$用于视频总结、重点提取和笔记整理的内容效率 Agent。$$,
    $$["Summarize long videos","Extract key takeaways","Create action-item notes"]$$::jsonb,
    $$["总结长视频","提取核心观点","生成行动项笔记"]$$::jsonb,
    $$[{"question":"Does it download videos?","answer":"No. It works from provided transcripts or supported links."},{"question":"Can it summarize in Chinese?","answer":"Yes. English and Chinese output fields are supported."}]$$::jsonb,
    $$[{"question":"它会下载视频吗？","answer":"不会。它基于提供的字幕或支持的链接工作。"},{"question":"可以用中文总结吗？","answer":"可以。系统支持中英文输出字段。"}]$$::jsonb,
    $$Provide a transcript or supported video link, then select summary format and output language.$$,
    $$提供字幕或支持的视频链接，然后选择总结格式和输出语言。$$,
    $$Uses user-provided links or transcripts. Avoid uploading private videos without rights.$$,
    $$使用用户提供的链接或字幕。请勿上传无权使用的私密视频。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'resume-career-coach-agent',
    'platform',
    'approved',
    false,
    true,
    (select id from public.agent_categories where slug = 'education'),
    array['resume', 'career', 'coaching'],
    'one_time',
    129,
    899,
    'hosted_agent',
    array['en', 'zh'],
    'https://demo.example.com/agents/resume-career-coach',
    true,
    4.60,
    10,
    20,
    52,
    $$Resume / Career Coach Agent$$,
    $$简历与职业教练 Agent$$,
    $$Reviews resumes and prepares practical interview coaching notes.$$,
    $$优化简历并生成实用面试辅导建议。$$,
    $$A career coaching assistant for resume review, role matching, interview preparation, and follow-up drafts.$$,
    $$用于简历优化、岗位匹配、面试准备和跟进邮件草稿的职业教练助手。$$,
    $$["Review resume structure","Suggest role-specific improvements","Prepare interview practice prompts"]$$::jsonb,
    $$["审核简历结构","提出岗位相关优化建议","生成面试练习问题"]$$::jsonb,
    $$[{"question":"Does it guarantee job offers?","answer":"No. It improves preparation and materials but cannot guarantee outcomes."},{"question":"Can it support bilingual resumes?","answer":"Yes. English and Chinese workflows are supported."}]$$::jsonb,
    $$[{"question":"它能保证拿到 offer 吗？","answer":"不能。它提升材料和准备质量，但不保证结果。"},{"question":"可以支持双语简历吗？","answer":"可以。支持中英文工作流。"}]$$::jsonb,
    $$Upload resume content, target role details, and preferred coaching language.$$,
    $$上传简历内容、目标岗位信息和偏好的辅导语言。$$,
    $$Uses resume and career goal information provided by the user. Remove sensitive identifiers when possible.$$,
    $$使用用户提供的简历和职业目标信息。建议尽量移除敏感身份信息。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  ),
  (
    'local-service-business-agent',
    'platform',
    'approved',
    false,
    true,
    (select id from public.agent_categories where slug = 'restaurant-local-business'),
    array['local-service', 'lead-capture', 'booking'],
    'one_time',
    399,
    2799,
    'website_chatbot',
    array['en', 'zh'],
    'https://demo.example.com/agents/local-service-business',
    true,
    4.50,
    12,
    25,
    69,
    $$Local Service Business Agent$$,
    $$本地服务商家 Agent$$,
    $$Captures local service requests and schedules follow-up calls.$$,
    $$收集本地服务需求并安排后续沟通。$$,
    $$A lead and support agent for local service companies such as repair, cleaning, moving, and wellness businesses.$$,
    $$适合维修、清洁、搬家和健康服务等本地服务商家的线索与客服 Agent。$$,
    $$["Collect service request details","Estimate urgency and location","Send follow-up notes to staff"]$$::jsonb,
    $$["收集服务需求","判断紧急程度和位置","向员工发送跟进信息"]$$::jsonb,
    $$[{"question":"Can it handle multiple service types?","answer":"Yes. Service categories and qualification questions are configurable."},{"question":"Can it quote prices?","answer":"It can show approved ranges or collect details for manual quotes."}]$$::jsonb,
    $$[{"question":"可以处理多种服务吗？","answer":"可以。服务分类和筛选问题都能配置。"},{"question":"可以报价吗？","answer":"可以展示已审核价格区间，或收集信息供人工报价。"}]$$::jsonb,
    $$Add service categories, coverage areas, intake questions, and team notification rules.$$,
    $$添加服务分类、覆盖区域、需求问题和团队通知规则。$$,
    $$Collects contact details, service needs, and location area. Exact address can be delayed until staff follow-up.$$,
    $$收集联系方式、服务需求和所在区域。详细地址可在人工跟进时再收集。$$,
    '1.0.0',
    $$Initial marketplace seed version.$$,
    $$初始演示版本。$$,
    '[]'::jsonb,
    null
  )
on conflict (slug) do update set
  owner_type = excluded.owner_type,
  status = excluded.status,
  is_featured = excluded.is_featured,
  is_verified = excluded.is_verified,
  category_id = excluded.category_id,
  tags = excluded.tags,
  pricing_type = excluded.pricing_type,
  price_usd = excluded.price_usd,
  price_cny = excluded.price_cny,
  delivery_type = excluded.delivery_type,
  supported_languages = excluded.supported_languages,
  demo_url = excluded.demo_url,
  demo_enabled = excluded.demo_enabled,
  rating = excluded.rating,
  review_count = excluded.review_count,
  purchase_count = excluded.purchase_count,
  install_count = excluded.install_count,
  title_en = excluded.title_en,
  title_zh = excluded.title_zh,
  short_description_en = excluded.short_description_en,
  short_description_zh = excluded.short_description_zh,
  description_en = excluded.description_en,
  description_zh = excluded.description_zh,
  features_en = excluded.features_en,
  features_zh = excluded.features_zh,
  faq_en = excluded.faq_en,
  faq_zh = excluded.faq_zh,
  setup_instructions_en = excluded.setup_instructions_en,
  setup_instructions_zh = excluded.setup_instructions_zh,
  data_permissions_en = excluded.data_permissions_en,
  data_permissions_zh = excluded.data_permissions_zh,
  version = excluded.version,
  changelog_en = excluded.changelog_en,
  changelog_zh = excluded.changelog_zh,
  screenshots = excluded.screenshots,
  video_url = excluded.video_url,
  updated_at = now();
